# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aspV2 <- function(BetaIn, EtaIn, HsIn, VnsIn, VnsidIn, VdsIn, XIn, ChiseqIn, SeIn, CnIn) {
    .Call('SVCM_aspV2', PACKAGE = 'SVCM', BetaIn, EtaIn, HsIn, VnsIn, VnsidIn, VdsIn, XIn, ChiseqIn, SeIn, CnIn)
}

aspV2NYU <- function(BetaIn, EtaIn, HsIn, VnsIn, VnsidIn, VdsIn, XIn, ChiseqIn, SeIn, CnIn, IXX) {
    .Call('SVCM_aspV2NYU', PACKAGE = 'SVCM', BetaIn, EtaIn, HsIn, VnsIn, VnsidIn, VdsIn, XIn, ChiseqIn, SeIn, CnIn, IXX)
}

mlrWresd <- function(X, Y) {
    .Call('SVCM_mlrWresd', PACKAGE = 'SVCM', X, Y)
}

rcpp_hello_world <- function() {
    .Call('SVCM_rcpp_hello_world', PACKAGE = 'SVCM')
}

siv <- function(RImg, XYZ, H) {
    .Call('SVCM_siv', PACKAGE = 'SVCM', RImg, XYZ, H)
}

